### PR TITLE
fix: Update openapi parser errors

### PR DESCRIPTION
**Pull request by dyadyaJora**
Hello!
I noticed couple errors in parsing of openapi specs and I tried to fix it with this PR. I am not sure that this files are single source of truth (but it looks like that).

Fixed errors:
* `paths.'/users/{userId}/ai/reports'. Declared path parameter userId needs to be defined as a path parameter in path or operation level`
*  `attribute paths.'/users/{userId}/security-logs/{securityLogId}'(get).parameters.[securityLogId].content is missing`

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@dyadyaJora thanks for reporting and fixing this!

This repository is not a source of truth for the API spec files, but I'll pass it on to the API team for a further fix.

**Comment by andrii-bodnar** [comment]
@dyadyaJora do you think there is a way to automate this to catch errors like this in the future? I am thinking of a CI step that will try to build these specifications. Could you please share what tool you used to build this?

**Comment by dyadyaJora** [comment]
I saw this errors with [swagger-parser-cli](https://github.com/swagger-api/swagger-parser) in openapi-generator. I am not sure that it would be the best choice for CI, but this library can determine whether your specification complies with the standard OpenAPI or not.

Probably it would be better for you to use not only validator projects but also linters like [oas-linter](https://www.npmjs.com/package/oas-linter) or [spectral-linter](https://www.npmjs.com/package/@stoplight/spectral-cli), which could be used like "eslint for OpenAPI".

**Comment by andrii-bodnar** [comment]
Thanks for sharing these details!

**Comment by andrii-bodnar** [comment]
#162

**Pull request closed without merging**
